factory_defaults = {"profile": "default", 
				"log": 7, 
				"timezone": 19, 
				"hostname": "",
				"wifi_ssid": "",
				"wifi_secret": "",
				"ha_topic": "hass",
				"ha_config": "homeassistant",
				"mqtt_server": "",
				"mqtt_username": "",
				"mqtt_password": "",
				"mqtt_ssl": True,
				"ntp_servers": [],
				"ntp_interval": 60,
				"module_wifi": True,
				"module_hass": False,
				}
